### ISSUE TITLE
Add pcall for the first run of neovim

### ISSUE THREAD

**Issue by voyeg3r** [elvessousa/.dotfiles#1]
When you run neovim for the first time we get an error message:

```
init.lua:34: Vim(colorscheme):E185: Cannot find color scheme 'sobrio_ghost'
```

Calling the colorscheme in a call we can avoid this error

```lua
local colorscheme = "sobrio_ghost"
local status_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
if not status_ok then
    print("colorscheme " .. colorscheme .. " not found!")
    return
end
```

**Comment by elvessousa** [comment]
Sergio, sorry for the delay. Only now I saw your suggestion. I'll implement it asap. Thank you!

**Comment by elvessousa** [comment]
I already pushed the code which fix this issue. Worked like a charm. Thanks a lot!
